version: '2.2'
services:
    mysql:
      image: mysql
      container_name: mysql_server
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: db
      ports:
        - "3307:3306"
      volumes:
        - ./mysql-data:/var/lib/mysql
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    phpmyadmin:
      image: nazarpc/phpmyadmin
      container_name: phpMyAdmin
      ports:
        - "8090:80"
      links:
        - mysql

    smog_api:
        build: smog-api
        container_name: smog_api
        ports:
          - "6333:3333"
        volumes:
          - ../app:/var/www/smog-api
        links:
          - mysql
volumes:
  mysql-data:
    driver: local

